# Generated by Django 4.2.4 on 2023-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='last_name',
            field=models.CharField(),
        ),
    ]
