# Generated by Django 4.2.4 on 2023-08-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('recipe_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe_book_app.recipe_book')),
            ],
        ),
    ]
